<?php declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Mega Menu Lite Hyva
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Amasty\MegaMenuLite\Api\Data\Menu\ItemInterface;
use Amasty\MegaMenuLiteHyva\ViewModel\DesktopMenuItem;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var array $item */

$label = !empty($item[ItemInterface::LABEL]) ? $item[ItemInterface::LABEL] : false;
$fontWeight = $item['mobile_font'] ?? '700';
$menuItemViewModel = $viewModels->require(DesktopMenuItem::class);

$additionalClass = $item['current'] ? 'text-[var(--ammenu-current-category-color)]'
    : 'text-[var(--ammenu-main-menu-text)]';
$bgClass = $item['current'] ? 'bg-[var(--ammenu-current-category-color)]'
    : 'bg-[var(--ammenu-main-menu-text)]';

$iconBlock = $block->getLayout()->getBlock('ammenu.top.menu.icon');

//phpcs:disable Generic.Files.LineLength.TooLong
?>
<a href="<?= $escaper->escapeUrl($item['url']) ?>"
   alt="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
   title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
   class="flex flex-col items-center w-full py-4 border-0 background-none break-anywhere text-start <?= $escaper->escapeHtmlAttr($additionalClass); ?>">

    <?php if (isset($item['icon'])): ?>
    <div class="submenu-item-image w-20 h-20" data-nosnippet="">
        <img class="w-full h-full object-contain" src="<?= $item['icon'] ?>" alt="<?= $escaper->escapeHtml($item['name']); ?>" loading="lazy">
    </div>
    <?php endif; ?>


    <span :style="{ 'font-weight': <?= $escaper->escapeHtmlAttr($fontWeight); ?> }">
        <?= $escaper->escapeHtml($item['name']); ?>
    </span>

    <?= /** @noEscape */ $menuItemViewModel->fetchView('components/label.phtml', [
        'item' => $item,
        'classes' => 'text-center inline-block text-xs font-bold rounded p-1 ml-2 mr-6 overflow-hidden'
    ]); ?>
</a>
