<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.itemsCount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            showItemCountTitle() {
               if (this.cart.summary_count > 1) {
                   return '<?= $escaper->escapeJs(__('products')) ?>';
               } else {
                   return '<?= $escaper->escapeJs(__('product')) ?>';
               }
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const itemData = this.cart.items.filter((item) => item['item_id'] === itemId);
                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0);

                    if (result.success && itemData) {
                        window.dispatchEvent(new CustomEvent('cart-item-removed', { detail: itemData }));
                    }

                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            scrollLock(use = true) {
                document.body.style.overflow = use ? "hidden" : "";
            },
            toggleCartDrawer(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    if (event.detail.isOpen) {
                        this.openCartDrawer();
                    } else {
                        this.open = false;
                        this.scrollLock(false);
                        this.$refs && this.$refs.cartDialogContent && hyva.releaseFocus(this.$refs.cartDialogContent);
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.openCartDrawer()
                }
            },
            openCartDrawer() {
                this.open = true;
                this.scrollLock(true);
                this.$nextTick(() => {
                    this.$refs && this.$refs.cartDialogContent && hyva.trapFocus(this.$refs.cartDialogContent)
                })
            },
            closeCartDrawer() {
                this.$dispatch('toggle-cart', { isOpen: false })
            },
            getSectionDataExtraActions() {
                if (!this.cart.extra_actions) {
                    return '';
                }

                const contentNode = document.createElement('div');
                contentNode.innerHTML = this.cart.extra_actions;

                hyva.activateScripts(contentNode);

                return contentNode.innerHTML;
            }
        }
    }
</script>
<section x-cloak
         x-show="cart"
         id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getData($event.detail.data)"
         @toggle-cart.window="toggleCartDrawer($event)"
         @keydown.escape="closeCartDrawer"
>
    <div role="dialog"
         aria-labelledby="cart-drawer-title"
         aria-modal="true"
         :aria-hidden="!open"
         class="relative z-30">
        <div class="backdrop"
             x-show="open"
             x-transition:enter="ease-in-out duration-100"
             x-transition:enter-start="opacity-0"
             x-transition:enter-end="opacity-100"
             x-transition:leave="ease-in-out duration-100"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
             role="button"
             @click="closeCartDrawer"
             aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"></div>
        <div class="relative"
             x-show="open"
             x-ref="cartDialogContent"
             role="region"
             :tabindex="open ? 0 : -1"
             aria-label="<?= $escaper->escapeHtmlAttr(__('My Cart')) ?>"

        >
            <div class="ct-mini-cart flex flex-col absolute bg-white text-black shadow-xl pt-6 md:pt-0">
                <?= $block->getChildHtml('cart-drawer.top'); ?>

                <?= $block->getChildHtml('cart-drawer.items.before'); ?>

                <template x-if="!itemsCount">
                    <div class="relative px-4 my-6 bg-white border-bs sm:px-6 border-container">
                        <span class="text-sm"><?= $escaper->escapeHtml(__('You have no items in your shopping cart.')) ?></span>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div class="relative grid px-1 sm:px-3 bg-white overflow-y-auto overscroll-y-contain">
                        <div class="w-full p-3 space-x-4 transition duration-150 ease-in-out rounded-lg">
                            <div class="float-left cart-subtotal"><div class="label text-sm"><?= $escaper->escapeHtml(__('Subtotal')) ?>:</div> <div class="amount"><span class="text-lg" x-html="cart.subtotal"></span></div></div>
                            <div class="total-count text-sm"> <b x-html="cart.summary_count"></b> <span x-html="showItemCountTitle()"></span></div>
                        </div>
                        <template x-for="item in cartItems">
                            <div class="flex items-start p-3 space-x-4 transition duration-150 ease-in-out rounded-lg">
                                <template x-if="item.product_has_url && item.is_visible_in_site_visibility">
                                    <a :href="item.product_url"
                                       class="w-4/12 !ml-0 border relative overflow-hidden border-solid product-image p-1 rounded-md"
                                       :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Product "%0"')) ?>', item.product_name)"
                                    >
                                        <img class="w-full border"
                                            :src="item.product_image.src"
                                            :width="item.product_image.width"
                                            :height="item.product_image.height"
                                            loading="lazy"
                                            :alt="item.product_name"
                                        />
                                    </a>
                                </template>
                                <template x-if="!item.product_has_url || !item.is_visible_in_site_visibility">
                                    <div class="w-4/12 !ml-0  border relative overflow-hidden border-solid">
                                        <img
                                            class="w-full"
                                            :src="item.product_image.src"
                                            :width="item.product_image.width"
                                            :height="item.product_image.height"
                                            loading="lazy"
                                            :alt="item.product_name"
                                        />
                                    </div>
                                </template>
                                <div class="w-8/12">
                                    <div>
                                        <a :href="item.product_url"
                                           class="text-sm hover:underline"
                                           :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Product "%0"')) ?>', item.product_name)"
                                        >
                                            <span x-html="item.product_name"></span>
                                        </a>
                                    </div>
                                    <div x-data="{ open: false }" class="relative inline-block text-sm"
                                         x-show="item.options && item.options.length > 0">
                                        <template x-if="item.options && item.options.length > 0">
                                            <div>
                                                <span @click="open = !open" class="text-blue-600 cursor-pointer flex items-center">
                                                    <?= $escaper->escapeHtml(__('See Details')); ?>
                                                    <?= $heroicons->chevronDownHtml("w-3 h-3 ml-2 transition-transform duration-200 details-dropdown", 20, 20, ['aria-hidden' => 'true', ':class' => '{ "rotate-180": open }']); ?>
                                                </span>
                                                <template x-for="option in item.options">
                                                    <div class="pt-2"  x-show="open" @click.outside="open = false">
                                                        <p class="font-bold mt-0 option-label" x-text="option.label"></p>
                                                        <p class="text-black option-value ml-0 mt-0" x-html="option.value"></p>
                                                    </div>
                                                </template>
                                            <div>
                                        </template>
                                    </div>
                                    <p><span x-html="item.product_price"></span></p>
                                    <div class="flex justify-between text-sm mt-2">
                                        <div class="qty">
                                            <span><?= $escaper->escapeHtml(__('Qty')); ?>:</span>
                                            <span x-html="item.qty"></span>
                                        </div>
                                        <div class="minicart-actions">
                                            <a :href="item.configure_url"
                                               x-show="item.product_type !== 'grouped' && item.is_visible_in_site_visibility"
                                               class="inline-flex mr-4"
                                               :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Edit product "%0"')) ?>', item.product_name)"
                                            >
                                                <?= $heroicons->pencilHtml('', 18, 18, ['aria-hidden' => 'true']); ?>
                                            </a>
                                            <button type="button"
                                                    class="inline-flex"
                                                    @click="deleteItemFromCart(item.item_id)"
                                                    :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Remove product "%0" from cart')) ?>', item.product_name)"
                                            >
                                                <?= $heroicons->xHtml('', 18, 18, ['aria-hidden' => 'true']); ?>
                                            </button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </template>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div>
                        <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

                        <div class="relative grid py-3 px-1 sm:px-3 bg-white">
                            <div class="w-full px-3 space-x-4 mb-4 transition duration-150 ease-in-out rounded-lg">
                                <a @click.prevent.stop="closeCartDrawer; $dispatch('toggle-authentication',
                                    {url: '<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>'});"
                                   href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                                   class="btn btn-primary w-full uppercase text-white viewcart font-semibold"
                                >
                                    <?= $escaper->escapeHtml(__('View and edit cart')) ?>
                                </a>
                            </div>
                            <div x-html="getSectionDataExtraActions()" class="w-full px-3"></div>
                            <div class="w-full px-3 space-x-4 transition duration-150 ease-in-out rounded-lg">
                                <a @click.prevent.stop="closeCartDrawer; $dispatch('toggle-authentication',
                                    {url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'});"
                                   href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                                   class="btn btn-primary w-full uppercase text-white checkout font-semibold"
                                >
                                    <?= $escaper->escapeHtml(__('Checkout')) ?>
                                </a>
                            </div>
                            <?= $block->getChildHtml('extra_actions'); ?>
                        </div>
                    </div>
                </template>

                <?= $block->getChildHtml('cart-drawer.bottom'); ?>
            </div>
        </div>
        <?= $block->getChildHtml('loading') ?>
    </div>

</section>
