<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="flex flex-col lg:flex-row-reverse lg:items-start gap-8">
    <div class="lg:w-80 2xl:w-96 lg:top-2 lg:pt-6">
        <div class="flex flex-col mb-2 pb-3 border-b border-solid">
            <strong class="text-center title-font font-base md:text-left text-base font-bold summary-title">
                <?= $escaper->escapeHtml(__('Summary')) ?>
            </strong>
        </div>
        <?= $block->getChildHtml('cart.summary') ?>
        <div class="product-social-links mt-8">
            <?= $block->getLayout()
                ->createBlock(\Magento\Cms\Block\Block::class)
                ->setBlockId('product_social_links')
                ->toHtml(); ?>
        </div>
    </div>
    <div class="lg:flex-1">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
        <?= $block->getChildHtml('cart.discount') ?>
    </div>
</div>
