<?php
/**
 * Copyright (c) 2018 MageModule, LLC: All rights reserved
 *
 * LICENSE: This source file is subject to our standard End User License
 * Agreeement (EULA) that is available through the world-wide-web at the
 * following URI: https://www.magemodule.com/end-user-license-agreement/.
 *
 *  If you did not receive a copy of the EULA and are unable to obtain it through
 *  the web, please send a note to admin@magemodule.com so that we can mail
 *  you a copy immediately.
 *
 *  @author        MageModule admin@magemodule.com
 *  @copyright    2018 MageModule, LLC
 *  @license        https://www.magemodule.com/end-user-license-agreement/
 */

/** @var \MageModule\Core\Block\Adminhtml\Media\Gallery\Content $block */
$elementName = $block->getElement()->getFieldName() . '[images]';
$formName    = $block->getFormName();
?>
<div id="<?php echo $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"productGallery":{"template":"#<?php echo $block->getHtmlId() ?>-template"}}'
     data-parent-component="<?php echo $block->escapeHtml($block->getParentComponent()) ?>"
     data-images="<?php echo $block->escapeHtml($block->getImagesJson()) ?>"
     data-types="<?php echo $block->escapeHtml($block->getImageTypesJson()) ?>"
>
    <?php if (!$block->getElement()->getReadonly()) : ?>
        <div class="image image-placeholder">
            <?php echo $block->getUploaderHtml() ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text"><?php echo __('Browse to find or drag image here') ?></p>
            </div>
        </div>
    <?php endif; ?>
    <?php foreach ($block->getImageTypes() as $typeData) :?>
        <input name="<?php echo $block->escapeHtml($typeData['name']) ?>"
               data-form-part="<?php echo $formName ?>"
               class="image-<?php echo $block->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?php echo $block->escapeHtml($typeData['value']) ?>"/>
    <?php endforeach ?>
    
    <script id="<?php echo $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item<% if (data.disabled == 1) { %> hidden-for-front<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?php echo $formName ?>"
                   class="position"/>
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][file]"
                   data-form-part="<?php echo $formName ?>"
                   value="<%- data.file %>"/>
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][value_id]"
                   data-form-part="<?php echo $formName ?>"
                   value="<%- data.value_id %>"/>
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][label]"
                   data-form-part="<?php echo $formName ?>"
                   value="<%- data.label %>"/>
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][disabled]"
                   data-form-part="<?php echo $formName ?>"
                   value="<%- data.disabled %>"/>
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?php echo $formName ?>"
                   value="image"/>
            <input type="hidden"
                   name="<?php echo $elementName ?>[<%- data.file_id %>][removed]"
                   data-form-part="<?php echo $formName ?>"
                   value=""
                   class="is-removed"/>
            
            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>
                
                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<?php echo __('Delete image') ?>">
                        <span><?php echo __('Delete image') ?></span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?php echo __('Hidden') ?></span></div>
            </div>
            <div class="item-description">
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                    <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>
            <ul class="item-roles" data-role="roles-labels">
                <?php foreach ($block->getImageTypes() as $typeData) : ?>
                    <li data-role-code="<?php echo $block->escapeHtml($typeData['code']) ?>"
                        class="item-role item-role-<?php echo $block->escapeHtml($typeData['code']) ?>">
                        <?php echo $block->escapeHtml($typeData['label']) ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </script>
    
    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
        <div class="image-panel" data-role="dialog">
        </div>
    </script>
    
    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
        <div class="image-panel-preview">
            <img src="<%- data.url %>" alt="<%- data.label %>"/>
        </div>
        <div class="image-panel-controls">
            <strong class="image-name"><%- data.label %></strong>
            
            <fieldset class="admin__fieldset fieldset-image-panel">
                <div class="admin__field field-image-description">
                    <label class="admin__field-label" for="image-description">
                        <span><?php echo __('Alt Text') ?></span>
                    </label>
                    
                    <div class="admin__field-control">
                            <textarea data-role="image-description"
                                      rows="3"
                                      class="admin__control-textarea"
                                      title="Image Description"
                                      name="<?php echo $elementName ?>[<%- data.file_id %>][label]"><%- data.label %></textarea>
                    </div>
                </div>
                
                <div class="admin__field field-image-role">
                    <label class="admin__field-label">
                        <span><?php echo __('Role') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getMediaAttributes() as $attribute) :
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-type"
                                               data-role="type-selector"
                                               data-form-part="<?php echo $formName ?>"
                                               type="checkbox"
                                               value="<?php echo $block->escapeHtml($attribute->getAttributeCode()) ?>"
                                        />
                                        <?php echo $block->escapeHtml($attribute->getFrontendLabel()) ?>
                                    </label>
                                </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>
                
                <div class="admin__field admin__field-inline field-image-size" data-role="size">
                    <label class="admin__field-label">
                        <span><?php echo __('Image Size') ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?php echo __('{size}') ?>"></div>
                </div>
                
                <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                    <label class="admin__field-label">
                        <span><?php echo __('Image Resolution') ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?php echo __('{width}^{height} px') ?>"></div>
                </div>

                <?php if ($block->getData('show_hide_from_page_option')) : ?>
                    <div class="admin__field field-image-hide">
                        <div class="admin__field-control">
                            <div class="admin__field admin__field-option">
                                <input type="checkbox"
                                       id="hide-from-page"
                                       data-role="visibility-trigger"
                                       data-form-part="<?php echo $formName ?>"
                                       value="1"
                                       class="admin__control-checkbox"
                                       name="<?php echo $elementName ?>[<%- data.file_id %>][disabled]"
                                <% if (data.disabled == 1) { %>checked="checked"<% } %> />

                                <label for="hide-from-page" class="admin__field-label">
                                    <?php echo __('Hide from Page') ?>
                                </label>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </fieldset>
        </div>
    </script>
    <?php echo $block->getChildHtml('new-video') ?>
</div>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
