<style>
.category-description .widget.block.block-static-block {margin-top:20px;margin-bottom:0}
.merken ul
{    padding-left: 0;
    margin-right: -24px;margin-left:-6px}
.merken ul li {       list-style: none;
    display: inline-block;
    width:19.5%;
    margin-bottom: 17px;
    margin-top: 0;
    margin-right: 0;
}
.merken ul li img {padding:5px 0}
.merken ul li img:hover {
    box-shadow: rgba(0, 0, 0, 0.4) 0px 7px 15px -5px;
    transition: all 0.3s ease 0s;
}

element.style {
    user-select: auto;
}
@media (max-width: 991px) {
.category-description .widget.block.block-static-block {margin-top:0px}
.merken ul {margin-bottom:0}
.merken ul li {    width: 32.2%; display:none; }
.merken ul li#mob {display:inline-block;padding:8px 20px 8px 2px!important;padding:15px;margin-bottom: 10px;}
}
</style>