<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomOption;
use Magento\Catalog\Block\Product\View\Options\Type\Select;
use Magento\Framework\Escaper;

/** @var Select $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$option = $block->getOption();
$product = $block->getProduct();

/** @var CustomOption $customOptionsViewModel */
$customOptionsViewModel = $viewModels->require(CustomOption::class);

?>
<div class=" py-2 last:mb-6 last:border-b w-full sm:w-1/2 items-center">
    <label class="label text-gray-700 text-left w-full flex gap-1 items-center"
           for="select_<?= $escaper->escapeHtmlAttr($option->getId()) ?>"
    >
        <span><?= $escaper->escapeHtml($option->getTitle()) ?></span>
        <?php if ($option->getIsRequire()): ?>
            <span class="sup text-sm option-require">*</span>
        <?php endif; ?>
    </label>
    <div class="text-gray-900 text-left w-full">
        <?= $customOptionsViewModel->getOptionHtml($option, $product); ?>
    </div>
</div>
