<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\ConfigurableProduct\Block\Product\View\Type\Configurable;
use Magento\Framework\Escaper;

/** @var Configurable $block */
/** @var Escaper $escaper */

$product = $block->getProduct();
$productId = $product->getId();
$attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($product->isSaleable() && count($attributes)): ?>

    <script>
        function initConfigurableDropdownOptions_<?= (int) $productId ?>() {
            return initConfigurableOptions(
                '<?= (int) $productId ?>',
                <?= /* @noEscape */ $block->getJsonConfig() ?>
            );
        }
    </script>

    <div x-data="initConfigurableDropdownOptions_<?= (int) $productId ?>()"
         @private-content-loaded.window="onGetCartData($event.detail.data)"
         class="mb-6"
    >
        <?php foreach ($attributes as $attribute): ?>
            <?php $attributeId = $attribute->getAttributeId(); ?>
        <div class="pb-2 pt-4 w-full items-center product-configurable-option sm:w-1/2 relative">

            <label class="w-full text-left text-gray-700 label flex items-center gap-1"
                   for="attribute<?= $escaper->escapeHtmlAttr($attributeId) ?>"
            >
                <span>
                    <?= $escaper->escapeHtml($attribute->getProductAttribute()->getStoreLabel()) ?>
                </span>
                <span class="sup text-sm option-require">*</span>
            </label>
            <div class="w-full text-left text-gray-900">
                <select name="super_attribute[<?= $escaper->escapeHtmlAttr($attributeId) ?>]"
                        id="attribute<?= $escaper->escapeHtmlAttr($attributeId) ?>"
                        class="form-select super-attribute-select max-w-full w-full"
                        x-on:change="changeOption(<?= (int) $attributeId ?>, event.target.value)"
                        required>
                    <option value="">
                        <?= $escaper->escapeHtml(__('Choose an Option...')) ?>
                    </option>
                    <template
                        x-for="(item, index) in getAllAttributeOptions(<?= (int) $attributeId ?>)"
                        :key="item.id"
                    >
                        <template x-if="optionIsEnabled(<?= (int) $attributeId ?>, item.id)">
                        <option
                            :value="item.id"
                            x-html="getAttributeOptionLabel(item)"
                            :disabled="!optionIsActive(<?= (int) $attributeId ?>, item.id)"
                            :selected="selectedValues[<?= $escaper->escapeHtmlAttr($attributeId) ?>] === item.id">
                        </option>
                        </template>
                    </template>
                </select>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
<?php endif;?>
