<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div
    class="relative inline-block"
    x-data="{ open: false }"
    @keyup.escape="open = false"
    @click.outside="open = false"
>
    <button
        type="button"
        id="customer-menu"
        class="block rounded"
        @click="open = !open"
        :aria-expanded="open ? 'true' : 'false'"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
        aria-haspopup="true"
    >
        <svg height="35" viewBox="0 0 264 314" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">
            <!-- Bỏ bớt metadata không cần thiết -->
            <g>
              <ellipse cx="131.93" cy="76.76" rx="65.75" ry="65" fill="none" stroke="#67ae44" stroke-width="24"></ellipse>
              <path d="M131.94,372.21 C90.55,372.21 57,318.38 57,251.99 C57,185.59 90.55,131.76 131.94,131.76" fill="none" stroke="#67ae44" stroke-width="24" stroke-miterlimit="10" transform="rotate(90 131.93,251.99)"></path>
              <path d="M252,301.76 L252.16,251.69" fill="none" stroke="#67ae44" stroke-width="24"></path>
              <path d="M12,301.83 L11.71,250.34" fill="none" stroke="#67ae44" stroke-width="24"></path>
              <ellipse cx="12" cy="301.76" rx="12" ry="12" fill="#67ae44"></ellipse>
              <ellipse cx="252" cy="301.76" rx="12" ry="12" fill="#67ae44"></ellipse>
            </g>
        </svg>
    </button>
    <nav
        class="
            absolute right-0 w-40 py-2 mt-2 -mr-4 px-1 overflow-auto origin-top-right rounded-sm
            shadow-lg sm:w-48 lg:mt-3 bg-container-lighter
        "
        x-cloak
        x-show="open"
        aria-labelledby="customer-menu"
        style="z-index: 51"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <?= $block->getChildHtml('header.customer.logged.in.links') ?>
        <?php else: ?>
            <?= $block->getChildHtml('header.customer.logged.out.links') ?>
        <?php endif; ?>
    </nav>
</div>
