<?php
/**
 * @var $block \RedChamps\ShareCart\Block\Buttons\MiniCart\Button
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<button id="<?= /* @noEscape */$block->getContainerId()?>" type="button" class="btn btn-primary w-full action primary checkout share-cart-btn checkout my-4 justify-center text-white uppercase text-sm font-semibold"  title="Share Shopping Cart">
    <span class="mx-auto"><?= /* @noEscape */__('Share Shopping Cart')?></span>
</button>
