<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'grand_total' && checkoutConfig.includeTaxInGrandTotal">
    <div>
        <div class="flex px-0 text-xl md:grid md:grid-cols-2 md:w-full border-b border-container subtotal-block">
            <div class="w-7/12 text-base font-bold pb-0 px-0 text-left md:w-auto inline-block"
                 x-html="`${segment.title} ${includingTaxMessage}` "
            ></div>
            <div class="w-5/12 text-right md:w-auto font-normal text-right text-black"
                 x-text="hyva.formatPrice(segment.value)"
            ></div>
        </div>

        <div class="flex px-0 text-md md:grid md:grid-cols-2 md:w-full subtotal-block">
            <div class="w-7/12 text-base font-bold pb-0 px-0 text-left md:w-auto inline-block"
                 x-html="`${segment.title} ${excludingTaxMessage}` "
            ></div>
            <div class="w-5/12 text-right md:w-auto font-normal text-right text-black"
                 x-text="hyva.formatPrice(totalsData.grand_total)"
            ></div>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'grand_total' && !checkoutConfig.includeTaxInGrandTotal">
    <div class="flex px-0 text-2xl md:grid md:grid-cols-2 md:w-full subtotal-block">

        <div class="w-7/12 text-base font-bold pb-0 px-0 text-left md:w-auto inline-block"
             x-html="`${segment.title}`"
        ></div>
        <div class="w-5/12 text-base text-right md:w-auto font-bold text-right text-black"
             x-text="hyva.formatPrice(segment.value)"
        ></div>


    </div>
</template>
