<?php
$params = $this->getData('params');
$helper = $this->helper('Biztech\Deliverydate\Helper\Data');
$isMandatory = $block->getisMandatory();
//$deliverydateLabel = $block->getDeliverydatelabel();
//$deliverydateLabel = $deliverydateLabel ? $deliverydateLabel . ':' : 'Delivery Date:';
$deliverydateCommentsLabel = $block->getDeliveryDateCommentsLabel();
$deliverydateCommentsLabel = $deliverydateCommentsLabel ? $deliverydateCommentsLabel . ':' : 'Delivery Comments:';
$timeslotTableLabel = $block->getTableLabel();
$timeslotTableLabel = $timeslotTableLabel ? $timeslotTableLabel : 'Timeslot\'s';
$class = 'input-text admin__control-text';
if ($helper->isEnable()) {
    ?>
    <div id="delivery-date_section" class="admin__page-section-item">
        <fieldset class="admin__fieldset">


            <div class="admin__form-field">

                <div class="admin__form-field-control field-delivery-date"
                     data-ui-id="shipping_arrival_date">
                    <label class="label admin__field-label" for="shipping_arrival_date"
                           data-ui-id="shipping_arrival_date">
                        <strong><?php echo __('New Delivery Date') ?></strong>
                    </label>

                    <div class="admin__field-control value datepicker-update">
                        <?php
                        echo $this->getLayout()
                                ->createBlock('Biztech\Deliverydate\Block\Adminhtml\UpdateDate')
                                ->setName('shipping_arrival_date')
                                ->setId('shipping_arrival_date')
                                ->setClass($class)
                                ->setExtraParams('readonly')
                                ->setCalendarTime($block->getCalendarTime())
                                ->setImage($this->getViewFileUrl('Magento_Theme::calendar.png'))
                                ->setTimeFormat($helper->convertDateFormatToJQueryUi($block->getDeliveryTimeFormat()))
                                ->setDateFormat($helper->convertDateFormatToJQueryUi($block->getDeliveryDateFormat()))
                                ->setCloseText(__('Done'))
                                ->setChangeYear(true)
                                ->setChangeMonth(true)
                                ->setMinDate('new Date()')
                                ->setShowOn('both')
                                ->getHtml();
                        ?>
                    </div>
                </div>
            </div>
            <div class="admin__form-field">
                <div class="admin__field field field-delivery-date-comment" data-ui-id="shipping_arrival_slot">
                    <label class="label admin__field-label" for="shipping_arrival_slot"
                           data-ui-id="shipping_arrival_slot">
                        <strong><?php echo __($timeslotTableLabel) ?></strong>
                    </label>

                    <div class="admin__field-control value">
                        <select name="shipping_arrival_slot" id="calandertimeslot">
                            <option value=""> <?php echo __("-- Select Timeslot --") ?> </option>
                            <?php
                            foreach ($helper->getTimeSlots() as $key => $value) {
                                $timePeriod = $value['start_time'] . ' - ' . $value['end_time']
                                ?>
                                <option value="<?php echo $timePeriod ?>"> <?php echo $timePeriod ?> </option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="admin__form-field">
                <div class="admin__field field field-delivery-date-comment" data-ui-id="shipping_arrival_comments">
                    <label class="label admin__field-label" for="shipping_arrival_comments"
                           data-ui-id="shipping_arrival_comments">
                        <strong><?php echo __($deliverydateCommentsLabel) ?></strong>
                    </label>

                    <div class="admin__field-control value">
                        <textarea cols="65" rows="8" name="shipping_arrival_comments"
                                  id="shipping_arrival_comments"></textarea>
                    </div>
                </div>
            </div>
            <div class="hidden-values">
                <input type="hidden" name="shipping_arrival_date" id="shipping_arrival_date"/>
            </div>
            <div id="update-deliverydate">Update Delivery Date</div>
            <input type="hidden" id="orderid" name="orderid"/>
            <input type="hidden" id="orderedate" name="orderedate"/>
            <input type="hidden" id="orderetimeslot" name="orderetimeslot"/>
            <script>
                document.getElementById("orderid").value = "<?= $params['order_id'] ?>";
                document.getElementById("orderedate").value = "<?= $params['shipping_arrival_date'] ?>";
                document.getElementById("orderetimeslot").value = "<?= $params['aSlot'] ?>";
            </script>
            <script>
                require([
                    "jquery",
                    'Magento_Ui/js/modal/alert',
                    'mage/url',
                    "mage/calendar",
                    'mage/translate'
                ], function ($, alert, getUrl) {
                    //                    jQuery('#shipping_arrival_comments').blur(function (event) {
                    //                        var params = {
                    //                            shipping_arrival_comments: $('#shipping_arrival_comments').val()
                    //                        }
                    //
                    //                        jQuery.ajax({
                    //                            url: "<?php //echo $this->getUrl('deliverydate/order/SaveDeliverydateComment');          ?>",
                    //                            type: 'POST',
                    //                            data: params,
                    //                        })
                    //                                .done(function (response) {
                    //                                    order.loadArea('totals', true);
                    //                                    jQuery('#order-totals').html(response);
                    //                                });
                    //
                    //                    });

                    jQuery(document).ready(function () {
                        $(document).on('click', '#update-deliverydate', function (event) {
                            if (!$('#shipping_arrival_date').val()) {
                                event.preventDefault();
                                alert({
                                    title: $.mage.__('Attention'),
                                    content: $.mage.__('Please Select Delivery Date'),
                                    actions: {
                                        always: function () {}
                                    }
                                });
                            } else if (!jQuery('#calandertimeslot').val() && $('#shipping_arrival_date').val()) {
                                event.preventDefault();
                                alert({
                                    title: $.mage.__('Attention'),
                                    content: $.mage.__('Please Select  A Timeslot'),
                                    actions: {
                                        always: function () {}
                                    }
                                });
                            } else {
                                var selected_Date = $('#shipping_arrival_date').val();
                                var selected_Timeslot = $('#calandertimeslot').val();
                                var order_id = $('#orderid').val();
                                var order_Date = $('#orderedate').val();
                                var order_Timeslot = $('#orderetimeslot').val();
                                var comments = $('#shipping_arrival_comments').val();
                                if (order_Timeslot == '' || order_Timeslot == null) {
                                    selected_Timeslot = null;
                                    order_Timeslot = null;
                                }
                                $.ajax({
                                    type: 'POST',
                                    url: '<?php echo $this->getUrl("deliverydate/order/updatedeliverydate") ?>',
                                    data: {selectedDate: selected_Date, selectedTimeslot: selected_Timeslot, orderId: order_id, ordereDate: order_Date, ordereTimeslot: order_Timeslot, comments: comments},
                                    dataType: 'json',
                                    success: function (data) {
                                        if (data.status == 'Success') {
                                            window.location = '<?php echo $this->getUrl("sales/order/view/order_id/" . $params['order_id']) ?>';
                                        }
                                        if (data.status == 'Error') {
                                            window.location = '<?php echo $this->getUrl("sales/order/view/order_id/" . $params['order_id']) ?>';
                                        }
                                    }
                                });
                            }
                        });
                    });
                });
            </script>
        </fieldset>
    </div>
<?php } ?>