<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ConvertImageWebp
 * @author     Extension Team
 * @copyright  Copyright (c) 2021-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/* @var \Bss\ConvertImageWebp\Block\System\Config\Webp\Button\ClearAllImages $block */
?>
<div class="pp-buttons-container">
    <p>
        <button id="clear_image_webp"
                onclick="confirmSetLocation('<?= /* @escapeNotVerified */  __('Are you sure you want to delete all webp images? Re generation can take a long time.') ?>', '<?php /* @escapeNotVerified */ echo $block->getUrl('bss_webp/webp/clearallimages') ?>')"
                type="button">
            <?= /* @escapeNotVerified */  __('Clear All Webp Images') ?>
        </button>
    </p>
</div>
