<?php if ($block->getHelper()->supportCookieDirective()): ?>
    <template data-consent="true">
        <div class="ec-gtm-cookie-directive" data-google="anowave gtm" data-check="<?php echo $block->getCheckAll() ?>">
        	<div>
        		<div>
        			<div>
        				<p><strong><?php echo __('Cookie Settings') ?></strong></p>
        				<p><?php echo sprintf($block->getHelper()->getCookieDirectiveContent(),$block->getHelper()->getStore()->getName()) ?></p>
        			</div>
        			<?php if ($block->getHelper()->getCookieDirectiveIsSegmentMode()):?>
            			<div class="ec-gtm-cookie-directive-customize">
                			<div class="ec-gtm-cookie-directive-segments">
                				<div>
                					<input type="checkbox" checked="checked" disabled />
                					<label><?php echo __('Essential cookies') ?></label>
                					<a class="ec-gtm-cookie-directive-note-toggle" data-show="<?php echo __('Learn more')?>" data-hide="<?php echo __('Hide')?>"><?php echo __('Learn more')?></a>
                					<div class="ec-gtm-cookie-directive-note">
                						<small><?php echo __('These cookies are essential so that you can move around the website and use its features. Without these cookies services you have asked for cannot be provided.') ?></small>
                					</div>
                				</div>
                				<?php foreach ($block->getSegments() as $key => $segment):?>
                					<div>
                						<input type="checkbox" name="cookie[]" data-consent="<?php echo $key ?>" value="<?php echo $key ?>" id="consent_<?php echo $key ?>" <?php if ($segment['check']):?>checked="checked"<?php endif ?> />
                						<label for="consent_<?php echo $key ?>"><?php echo $segment['label'] ?></label>
                						<a class="ec-gtm-cookie-directive-note-toggle" data-show="<?php echo __('Learn more')?>" data-hide="<?php echo __('Hide')?>"><?php echo __('Learn more')?></a>
                						<div class="ec-gtm-cookie-directive-note">
                							<small><?php echo $segment['value'] ?></small>
                						</div>
                					</div>
                				<?php endforeach ?>
                				<div data-consent-uuid-wrapper>
                    				<a class="ec-gtm-cookie-directive-note-toggle" data-show="<?php echo __('Show consent details')?>" data-hide="<?php echo __('Close consent details')?>"><?php echo __('Show consent details')?></a>
                					<div class="ec-gtm-cookie-directive-note ec-gtm-cookie-directive-note-consent">
                						<small>
                    						<div>Your consent ID:</div>
                    						<div data-consent-uuid></div>
                						</small>
                					</div>
                    			</div>
                			</div>
                		</div>
        			<?php else: ?>
        				<div data-consent-uuid-wrapper>
            				<small>
        						<div>Your consent ID:</div>
        						<div data-consent-uuid></div>
    						</small>
            			</div>
        			<?php endif ?>
        			<div>
        				<?php if ($block->getSegmentMode()): ?>
        					<a class="action accept" data-confirm="<?php echo $block->getHelper()->getConfig('ec/cookie/content_text_confirm') ?>"><?php echo $block->getHelper()->getConfig('ec/cookie/content_text_accept') ?></a>
        				<?php endif ?>
        				<a class="action accept-all" data-confirm="<?php echo $block->getHelper()->getConfig('ec/cookie/content_text_confirm') ?>"><?php echo $block->getHelper()->getConfig('ec/cookie/content_text_accept_all') ?></a>
        				<?php if ($block->getHelper()->getCookieDirectiveShowDeclineButton()): ?>
        					<a class="action decline"><?php echo $block->getHelper()->getConfig('ec/cookie/content_text_decline') ?></a>
        				<?php endif ?>
        				<?php if ($block->getHelper()->getCookieDirectiveIsSegmentMode()): ?>
        					<a class="action customize" data-show="<?php echo $block->getHelper()->getConfig('ec/cookie/content_text_cuztomize') ?>" data-hide="<?php echo $block->getHelper()->getConfig('ec/cookie/content_text_cuztomize_close') ?>"><?php echo $block->getHelper()->getConfig('ec/cookie/content_text_cuztomize') ?></a>
        				<?php endif ?>
        				<?php if ((null !== $learn = $block->getHelper()->getConfig('ec/cookie/content_link_learn')) && 0 < strlen($learn)): ?>
        					<a class="action refuse" href="<?php echo $learn ?>" target="_blank"><?php echo $block->getHelper()->getConfig('ec/cookie/content_text_learn') ?></a>
        				<?php endif ?>
        				<a class="action close">
        					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
        						<path fill="<?php echo $block->getHelper()->getCookieDirectiveCloseIconBackgroundColor() ?>" d="M5.29289 5.29289C5.68342 4.90237 6.31658 4.90237 6.70711 5.29289L12 10.5858L17.2929 5.29289C17.6834 4.90237 18.3166 4.90237 18.7071 5.29289C19.0976 5.68342 19.0976 6.31658 18.7071 6.70711L13.4142 12L18.7071 17.2929C19.0976 17.6834 19.0976 18.3166 18.7071 18.7071C18.3166 19.0976 17.6834 19.0976 17.2929 18.7071L12 13.4142L6.70711 18.7071C6.31658 19.0976 5.68342 19.0976 5.29289 18.7071C4.90237 18.3166 4.90237 17.6834 5.29289 17.2929L10.5858 12L5.29289 6.70711C4.90237 6.31658 4.90237 5.68342 5.29289 5.29289Z"/>
        					</svg>
        				</a>
        			</div>
        		</div>
        	</div>
        </div>
    </template>
<?php endif ?>