<script data-ommit="true" nonce="<?php echo $block->generateNonce() ?>">

    document.addEventListener("DOMContentLoaded", () => 
    {
    	var PromotionTrack = ((dataLayer) => 
	    {
	        return {
	            apply: () => 
	            {
	                var promotions = [], position = 0;
	
	                document.querySelectorAll('[data-promotion]').forEach(promotion => 
	                {
						let entity =
						{
							promotion_id: 	promotion.dataset.promotionId,
							promotion_name: promotion.dataset.promotionName,
							creative_name:	promotion.dataset.promotionCreative,
							creative_slot:	promotion.dataset.promotionPosition
                        };

	                	AEC.EventDispatcher.trigger('ec.cookie.promotion.entity', entity, 
	    	            {
		    	            element: promotion
		    	        });

	                    promotions.push(entity);

	                    promotion.addEventListener('click', (event) => 
	                    {
	                    	var data = 
	                        {
                       			'event': 'select_promotion',
                                'ecommerce': 
                                {
                                    'items':
                                    [
                                    	{
                                    		promotion_id: 	event.target.dataset.promotionId,
                							promotion_name: event.target.dataset.promotionName,
                							creative_name:	event.target.dataset.promotionCreative,
                							creative_slot:	event.target.dataset.promotionPosition
                                    	}
                                    ]
                                }
			                };
			                
                            AEC.Cookie.promotionClick(data, promotion).push(dataLayer);

                            /**
                             * Save persistent data
                             */
                            AEC.Persist.push(AEC.Persist.CONST_KEY_PROMOTION,
	                        {
    	                        'promotion': data.ecommerce.items[0]
    	                    });
		                });
	                });
	
	                if (promotions.length)
	                {
		                AEC.Cookie.promotion(
				        {
	                        'event':'view_promotion',
                            'ecommerce':
                            {
                                'items': promotions
                            }
                        }).push(dataLayer);
	                }
	
	                return this;
	            }
	        }
	    })(dataLayer).apply();
    });
</script>