<script data-ommit="true" nonce="<?php echo $block->generateNonce() ?>">

    document.addEventListener("DOMContentLoaded", () => 
    {
    	(() => 
    	{
    		let map = {}, trace = {};
    
    		document.querySelectorAll('[data-widget]').forEach((element) => 
            {
                let widget = element.dataset.widget;

                let entity = 
    			{
    					
    				item_id: 		element.dataset.id,
    				item_name: 		element.dataset.name,
    				item_list_name: element.dataset.list,
    				item_list_id:	element.dataset.list,
    				item_brand: 	element.dataset.brand,
    				category:		element.dataset.category,
    				price: 			parseFloat(element.dataset.price),
    				index: 			parseFloat(element.dataset.position),
    				currency:		AEC.GA4.currency,
    				quantity: 		1,
    				google_business_vertical: 'retail'
    			};

                Object.assign(entity, entity, AEC.GA4.augmentCategories(entity));

            	let attributes = element.dataset.attributes;
                
            	if (attributes)
    	        {
        	        Object.entries(JSON.parse(attributes)).forEach(([key, value]) => 
        	        {
            	        entity[key] = value;
        	        });
        	    }

        	    if (!map.hasOwnProperty(widget))
        	    {
            	    map[widget] = [];
            	    
            	    map[widget].trace = {};
            	    map[widget].entry = [];
            	    map[widget].item_list_id = '';
            	    map[widget].item_list_name = '';
        	    }

        	    if (!map[widget].trace.hasOwnProperty(element.dataset.id))
        	    {
        	    	map[widget].trace[element.dataset.id] = true;
            	    
            	    map[widget].entry.push(entity);

            	    map[widget].item_list_id 	= entity.item_list_id;
            	    map[widget].item_list_name 	= entity.item_list_name;
        	    } 
            });

    		Object.entries(map).forEach(([key, value]) => 
	        {
		        if (value.entry.length)
		        {
    		        let data = 
    			    {
    					event: 'view_item_list',
    					ecommerce:
    					{
    						item_list_id: 	value.item_list_id,
    						item_list_name: value.item_list_name,
    						items: 			value.entry
    					}
    				};

    		        if ('undefined' !== typeof dataLayer)
    				{
    					(function(callback)
    					{
    						if (AEC.Const.COOKIE_DIRECTIVE)
    						{
    							AEC.CookieConsent.queue(callback).process();
    						}
    						else 
    						{
    							callback.apply(window,[]);
    						}
    					})
    					(
    						(function(dataLayer, data)
    						{
    							return function()
    							{
    								AEC.EventDispatcher.trigger('ec.widget.view.data', data);

    								if (AEC.reset)
    								{
    									dataLayer.push({ ecommerce: null });
    								}
    								
    								dataLayer.push(data);
    							}
    						})(dataLayer, data)
    					);
    				}
		        }
	        });
    	})();
    });
	
</script>