<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_CreditLimit
 * @author    CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
 ?>
<div class="payment-method-billing-address">
    <span><?= $block->escapeHtml(__('Available Credit Amount:'));?></span>
    <span><?=$block->getRemainingLimit()?></span>
</div>
