<?php declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Mega Menu Pro Hyva
 */

use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Amasty\MegaMenuLite\Block\Container;
use Amasty\MegaMenuLiteHyva\ViewModel\DesktopMenuItem;

/** @var Escaper $escaper */
/** @var Container $block */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroIcons */
/** @var array $item */
/** @var array $parentItem */

$heroIcons = $viewModels->require(HeroiconsOutline::class);
$menuItemViewModel = $viewModels->require(DesktopMenuItem::class);
$menuItemViewModel->setBlock($block);

$elems = $item['elems'] ?? [];
$content = $item['mobile_content'] ?? '';
$fontWeight = $item['mobile_font'] ?? '700';
$additionalClass = $item['current'] ? 'text-[var(--ammenu-current-category-color)]'
    : 'text-[var(--ammenu-submenu-text)]';
$showMobileContent = $item['show_mobile_content'] ?? false;
$iconBlock = $block->getLayout()->getBlock('ammenu.top.menu.icon');

// phpcs:disable Generic.Files.LineLength.TooLong
?>
<template x-if="'<?= $escaper->escapeHtmlAttr($item['id']); ?>' === drillActiveId">
    <div class="mx-4"
         :class="{
             'animate-slide_right': isPreviousItem,
             'animate-slide_left': !isPreviousItem
         }" :style="{ 'border-color': colorize(color_settings.toggle_icon_color).getLighten(0.16) }">
        <ul>
            <li class="border-b border-inherit flex items-center py-4 text-[var(--ammenu-main-menu-text)]"
                x-cloak>
                <button
                    class="flex items-center"
                    @click.prevent="drillTabs = []; drillActiveId = ''"
                    @keydown.enter.prevent="drillTabs = []; drillActiveId = ''"
                    @keydown.space.prevent="drillTabs = []; drillActiveId = ''"
                    tabindex="0"
                    >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44.93 54.17" fill="#67ae44" class="mr-2 arrow rotate-180">
                      <path d="M6.6,9.31,35.3,27.09,6.6,44.87V9.3M3.21,0A3.21,3.21,0,0,0,0,3.21V51a3.2,3.2,0,0,0,4.89,2.72L43.41,29.81a3.19,3.19,0,0,0,1-4.4,3.23,3.23,0,0,0-1-1L4.89.48A3.34,3.34,0,0,0,3.21,0Z"></path>
                    </svg>
                    <span>
                        <?= $escaper->escapeHtml(__("Products")) ?>
                    </span>
                </button>
            </li>
            <?php if (isset($parentItem)): ?>
                <li class="flex border-b border-inherit items-center py-4 text-[var(--ammenu-main-menu-text)] cursor-pointer"
                    @click.prevent="drillTabs.pop(); drillActiveId = drillTabs[drillTabs.length - 1]; isPreviousItem = true"
                    x-cloak>
                    <button
                        class="flex items-center"
                        @click.prevent="drillTabs.pop(); drillActiveId = drillTabs[drillTabs.length - 1]; isPreviousItem = true"
                        @keydown.enter.prevent="drillTabs.pop(); drillActiveId = drillTabs[drillTabs.length - 1]; isPreviousItem = true"
                        @keydown.space.prevent="drillTabs.pop(); drillActiveId = drillTabs[drillTabs.length - 1]; isPreviousItem = true"
                        tabindex="0">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44.93 54.17" fill="#67ae44" class="mr-2 arrow rotate-180">
                              <path d="M6.6,9.31,35.3,27.09,6.6,44.87V9.3M3.21,0A3.21,3.21,0,0,0,0,3.21V51a3.2,3.2,0,0,0,4.89,2.72L43.41,29.81a3.19,3.19,0,0,0,1-4.4,3.23,3.23,0,0,0-1-1L4.89.48A3.34,3.34,0,0,0,3.21,0Z"></path>
                        </svg>
                        <span>
                            <?= $escaper->escapeHtml($parentItem['name']); ?>
                        </span>
                    </button>
                </li>
            <?php endif ?>
        </ul>
        <div class="block items-center py-2">
            <?php if (isset($item['url'])): ?>
                <template x-if="!hide_view_all_link">
                    <span class="text-3xl text-[var(--ammenu-main-menu-text)]"
                          :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontWeight); ?>'">
                        <?= $escaper->escapeHtml($item['name']) ?>
                    </span>
                </template>
                <template x-if="hide_view_all_link">
                    <a class="block text-[var(--ammenu-main-menu-text)]"
                       href="<?= $escaper->escapeUrl($item['url']); ?>"
                       title="<?= $escaper->escapeHtmlAttr($item['name']); ?>">
                        <span class="text-2xl"
                              :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontWeight); ?>'">
                            <?= $escaper->escapeHtml($item['name']); ?>
                        </span>
                    </a>
                </template>
            <?php else: ?>
                <span :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontWeight); ?>'">
                    <?= $escaper->escapeHtml($item['name']) ?>
                </span>
            <?php endif; ?>
            <?= /** @noEscape */ $menuItemViewModel->fetchView('components/label.phtml', [
                'item' => $item,
                'classes' => 'inline-block text-center text-xs font-bold rounded p-1 ml-2 mr-6 overflow-hidden'
            ]); ?>
        </div>
        <?php if ($showMobileContent === 0 && !empty($content)): ?>
            <div class="flex justify-between items-center border-b border-inherit" data-content="ammenu-content">
                <?= /* @noEscape */ $content; ?>
            </div>
        <?php endif; ?>
        <ul class="border-inherit" :style="{
                '--ammenu-submenu-text': 'var(--ammenu-third-level-menu)'
            }">
            <template x-if="!hide_view_all_link">
                <li class="flex items-center border-b py-4 border-inherit">
                    <a href="<?= $escaper->escapeUrl($item['url']) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__("View All %1", $item['name'])) ?>"
                       class="block w-full underline text-md text-[var(--ammenu-submenu-text)]">
                        <?= $escaper->escapeHtml(__("View All %1", $item['name'])) ?>
                    </a>
                </li>
            </template>
            <?php foreach ($elems as $key => $itemChild): ?>
                <li class="flex items-center border-b py-4 border-inherit last:border-0">
                    <?php
                    $fontChildWeight = $itemChild['desktop_font'] ?? '400';
                    $elemsChild = $itemChild['elems'];
                    $additionalClass = $itemChild['current'] ? 'text-[var(--ammenu-current-category-color)]' : 'text-[var(--ammenu-submenu-text)]';
                    ?>
                    <?php if (!empty($elemsChild)): ?>
                        <button class="flex items-center text-start justify-between w-full <?= $escaper->escapeHtmlAttr($additionalClass); ?>"
                                title="<?= $escaper->escapeHtmlAttr($itemChild['name']); ?>"
                                @click.prevent="drillTabs.push('<?= $escaper->escapeHtmlAttr($itemChild['id']) ?>'); drillActiveId = '<?= $escaper->escapeHtmlAttr($itemChild['id']); ?>'; isPreviousItem = false">
                            <span class="flex items-center">
                                <?php if ($iconBlock): ?>
                                    <?= /* @noEscape */ $iconBlock->setData('item', $itemChild)
                                        ->setData('additional_class', $additionalClass)
                                        ->setData('available', ['desktop', 'both'])->toHtml() ?>
                                <?php endif ?>
                                <?php if (isset($item['url'])): ?>
                                    <template x-if="!hide_view_all_link">
                                        <span :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontChildWeight); ?>'">
                                            <?= $escaper->escapeHtml($itemChild['name']) ?>
                                        </span>
                                    </template>
                                    <template x-if="hide_view_all_link">
                                        <a href="<?= $escaper->escapeUrl($itemChild['url']); ?>"
                                           title="<?= $escaper->escapeHtmlAttr($itemChild['name']); ?>">
                                            <span :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontChildWeight); ?>'">
                                                <?= $escaper->escapeHtml($itemChild['name']); ?>
                                            </span>
                                        </a>
                                    </template>
                                <?php else: ?>
                                    <span :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontChildWeight); ?>'">
                                        <?= $escaper->escapeHtml($item['name']) ?>
                                    </span>
                                <?php endif; ?>

                                <?= /** @noEscape */ $menuItemViewModel->fetchView('components/label.phtml', [
                                    'item' => $itemChild,
                                    'classes' => 'inline-block text-center text-xs font-bold rounded p-1 ml-2 mr-6 overflow-hidden'
                                ]); ?>
                            </span>
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44.93 54.17" fill="#67ae44" class="ml-2 arrow">
                              <path d="M6.6,9.31,35.3,27.09,6.6,44.87V9.3M3.21,0A3.21,3.21,0,0,0,0,3.21V51a3.2,3.2,0,0,0,4.89,2.72L43.41,29.81a3.19,3.19,0,0,0,1-4.4,3.23,3.23,0,0,0-1-1L4.89.48A3.34,3.34,0,0,0,3.21,0Z"></path>
                            </svg>
                    <?php else: ?>
                        <a class="flex items-center w-full text-start no-underline <?= $escaper->escapeHtmlAttr($additionalClass); ?>"
                           href="<?= $escaper->escapeUrl($itemChild['url']); ?>"
                           title="<?= $escaper->escapeHtmlAttr($itemChild['name']); ?>">
                            <?php if ($iconBlock): ?>
                                <?= /* @noEscape */ $iconBlock->setData('item', $itemChild)
                                    ->setData('additional_class', $additionalClass)
                                    ->setData('available', ['desktop', 'both'])->toHtml() ?>
                            <?php endif ?>
                            <span :style="'font-weight: <?= $escaper->escapeHtmlAttr($fontChildWeight); ?>'">
                                <?= $escaper->escapeHtml($itemChild['name']) ?>
                            </span>
                            <?= /** @noEscape */ $menuItemViewModel->fetchView('components/label.phtml', [
                                'item' => $itemChild,
                                'classes' => 'inline-block text-center text-xs font-bold rounded p-1 ml-2 mr-6 overflow-hidden'
                            ]); ?>
                        </a>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
        <?php if ($showMobileContent === 1 && !empty($content)): ?>
            <div class="flex justify-between items-center border-t border-inherit" data-content="ammenu-content">
                <?= /* @noEscape */ $content; ?>
            </div>
        <?php endif; ?>
    </div>
</template>
<?php foreach ($elems as $key => $itemChild): ?>
    <?php if (!empty($itemChild['elems'])): ?>
        <?= /** @noEscape */ $menuItemViewModel->fetchView('components/mobile_menu/drill.phtml', [
            'item' => $itemChild,
            'parentItem' => $item
        ], 'Amasty_MegaMenuProHyva::%s'); ?>
    <?php endif ?>
<?php endforeach ?>
