<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                <div class="control">
                    <input type="number"
                           name="qty"
                           id="qty"
                           min="0"
                           value=""
                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                           class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                </div>
            </div>
            <?php endif; ?>

            <?php if ($block->isEnableAtProductPage()): ?>
                <div id="appjetty-deliverydate" data-bind="scope:'product-deliverydate'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    <script>
                        window.deliverydateConfig = <?php echo json_encode($block->getDeliveryDateConfig()); ?>;
                    </script>
                    <script type="text/x-magento-init">
                    {
                        "#appjetty-deliverydate": {
                            "Magento_Ui/js/core/app": {
                               "components": {
                                    "product-deliverydate": {
                                        "component": "Biztech_Deliverydate/js/product-deliverydate"
                                    }
                                }
                            }
                        }
                    }
                    </script>
                </div>
            <?php endif; ?>
            
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
