<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pric
$_bizHelper = $objectManager->create('Biztech\Deliverydate\Helper\Data');
$collection = $this->getOrders();
$dateFormat = '';
$date_format = $_bizHelper->getConfigValue('deliverydate/deliverydate_front_config/deliverydate_format');
$time_format = $_bizHelper->getConfigValue('deliverydate/deliverydate_front_config/deliverytime_format');
$delivery_method = $_bizHelper->getConfigValue('deliverydate/deliverydate_front_config/delivery_method');
$isTime = $_bizHelper->getConfigValue('deliverydate/deliverydate_general/deliverytime_enable_time');


if ($date_format == '') {
    $date_format = 'd/M/Y';
    $dateFormat = 'd/M/Y';
}

foreach ($collection as $order) {


    if ($time_format == '') {
        /*$dateFormat .= " , g:i a";*/
        $time_format = "g:i a";
    } else {
        if ($isTime && ($delivery_method == 1 && $order['shipping_arrival_slot'] == null)) {
            $date_format .= " " . $time_format;
        } else {
            $date_format .= " ";
        }
    }

    $shipping_arrival_date = $order['shipping_arrival_date'];
    ?>
    <tr>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php echo $order['increment_id'] ?>
        </td>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php echo $order['created_at'] ?>
        </td>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php echo $order['billing_firstname'] . " " . $order['billing_lastname'] ?>
        </td>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php echo $order['shipping_firstname'] . " " . $order['shipping_lastname'] ?>
        </td>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php //echo Mage::helper('core')->currency($order->getBaseGrandTotal(), true, false); ?>
            <?php echo $priceHelper->currency($order['base_grand_total'], true, false); ?>
        </td>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php echo $priceHelper->currency($order['grand_total'], true, false); ?>
        </td>
        <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
            <?php echo $order['status'] ?>
        </td>
        <td align="left" valign="top"
            style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC; white-space: nowrap;">
            <?php echo date($date_format, strtotime($shipping_arrival_date)) . ' ' . $order['shipping_arrival_slot']; ?>
        </td>
    </tr>
    <?php
}
?>