<?php
$proHelper = $this->helper('Biztech\Deliverydatepro\Helper\Data');
$basicHelper = $this->helper('Biztech\Deliverydate\Helper\Data');
$status = false;
$timervalue = '';
if ($basicHelper->isCuttoffEnable() && $proHelper->sameDayDeliveryTimer()) {
    $isOrderProcessingTime = false;
    $productRegistry = $basicHelper->objectManager()->get('\Magento\Framework\Registry')->registry('current_product');
    $deliveryOption = $proHelper->deliveryOption();
    if ($deliveryOption == 2 && isset($productRegistry)) {
        $isOrderProcessingTime = true;
        $orderProcessingTime = $proHelper->getProductWiseOrderProTime();
    }
    if ($isOrderProcessingTime) {
        if ($orderProcessingTime > 0) {
            $dayIntval = $orderProcessingTime;
        } else {
            $dayIntval = 0;
        }
    } else {
        $dayIntval = $basicHelper->getDayDiff();
    }
    $isProductwiseCuttoff = $basicHelper->isProductwiseCuttoff();
    if ($isProductwiseCuttoff) {
        if (isset($productRegistry)) {
            if ($productRegistry->getId()) {

                if ($productRegistry->getCutOffTimeHours() != "" || $productRegistry->getCutOffTimeHours() != NULL) {
                    $hours = $productRegistry->getCutOffTimeHours();
                } else {
                    $hours = 00;
                }
                if ($productRegistry->getCutOffTimeMinutes() != "" || $productRegistry->getCutOffTimeMinutes() != NULL) {
                    $minutes = $productRegistry->getCutOffTimeMinutes();
                } else {
                    $minutes = 00;
                }
                if ($productRegistry->getCutOffTimeSeconds() != "" || $productRegistry->getCutOffTimeSeconds() != NULL) {
                    $seconds = $productRegistry->getCutOffTimeSeconds();
                } else {
                    $seconds = 00;
                }
                $getCuttofValue = $hours . ',' . $minutes . ',' . $seconds;
            }
        }
    } else {
        $getCuttofValue = $basicHelper->getCuttoffValue();
    }
    if ((($getCuttofValue === "00,00,00") === false) && $dayIntval == 0) {
        $this->_timezone = $basicHelper->objectManager()->create('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
        $getCuttofValue = str_replace(",", ":", $getCuttofValue);
        $cutoffobj = new DateTime($this->_timezone->date()->format('Y-m-d') . " " . $getCuttofValue);
        $currenttimeobj = new DateTime($this->_timezone->date()->format('Y-m-d H:i:s'));
        if ($currenttimeobj < $cutoffobj) {
            $status = true;
        } else {
            $status = false;
        }
    } else {
        $status = false;
    }
}
if ($status == true) {
    ?>
    <div class="timer-end">
        <div class="timer-inner-box">
            <p class="timer-end-msg">
                <?php echo __('Same day delivery time ends in '); ?>
            </p>
            <p class="timer-end-warning" id="countdown">
                <?php // printf("Same day delivery time ends in %d hours, %d minutes, %d seconds", $hours, $minutes, $seconds);  ?>
            </p>
        </div>
    </div>

    <script>
    // Set the date we're counting down to
        var countDownDate = new Date("<?php echo $cutoffobj->format('M j, Y H:i:s') ?>").getTime();
    // Update the count down every 1 second
        var x = setInterval(function () {

            // Get today's date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = countDownDate - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Output the result in an element with id="demo"
            document.getElementById("countdown").innerHTML = hours + "h "
                    + minutes + "m " + seconds + "s ";

            // If the count down is over, write some text 
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("countdown").innerHTML = "EXPIRED";
            }
        }, 1000);
    </script>
<?php } ?>